#开发配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
     # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath*:/mapper/*Mapper.xml


#server:
#  port: 80
#spring:
#  messages:
#    basename: i18n/Messages,i18n/Pages
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
#    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
#    url: jdbc:mysql://localhost:3306/test           # 数据库连接地址
#    username: root                                  # 数据库用户名
#    password: mysqladmin                            # 数据库连接密码
#    dbcp2:                                          # 进行数据库连接池的配置
#      min-idle: 5                                   # 数据库连接池的最小维持连接数
#      initial-size: 5                               # 初始化提供的连接数
#      max-total: 5                                  # 最大的连接数
#      max-wait-millis: 200                          # 等待连接获取的最大超时时间